name: workflow:main:ci
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with Clang
        run: make -B build CC=clang
      - name: Build examples with Clang
        run: make -B build-examples CC=clang
      - name: Build with GCC
        run: make -B build CC=gcc
      - name: Build examples with GCC
        run: make -B build-examples CC=gcc
  quality-checks:
    name: Quality Checks & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Quality Checks
        run: make format-check
      - name: Test
        run: make test
