name: workflow:main:ci
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    name: Quality Checks, Build, & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quality Checks
        run: make format-check
      - name: Build
        run: make build
      - name: Test
        run: make test
